import * as React from "react";
import { generateCard } from "utils";

interface Props
    extends React.DetailedHTMLProps<
        React.ImgHTMLAttributes<HTMLImageElement>,
        HTMLImageElement
    > {
    card: number;
}

export default function CardImg(props: Props) {
    return (
        <img
            src={`data:image/svg+xml;base64,${btoa(generateCard(props.card))}`}
            {...props}
            // TODO: Add autogenerated alt
            alt={""}
        />
    );
}
